[grammar]
axiom = "F"

[grammar.rules]
# Ходовая «шахтная» ветвистая генерация с равномерными вкраплениями K (Shrine), M (Lair) и V (Villager Post)
F = "F[+K]F[-M]F(0.35), F[+V]F[-K]F(0.25), F[+F]F[-F]F(0.20), FF(0.20)"
K = "K(0.60), KF(0.40)"
M = "M(0.60), MF(0.40)"
V = "V(0.60), VF(0.40)"
