[dungeon]
grammar_file = "grammars/classic.toml"
iterations = 3

[dungeon.symbols]
F = { label = "Twisting corridor", tags = ["stone", "narrow", "torchlit"] }
K = { label = "Key shrine", tags = ["mystic", "glowing", "runes"] }
M = { label = "Beast lair", tags = ["musky", "clawed", "danger"] }

[ollama]
endpoint = "https://341f48ced197.ngrok-free.app"
completion_path = "/v1/completions"
model = "deepseek-r1:1.5b"
timeout = 120
prompt_file = "prompts/default_prompts.toml"

[ollama.options]
temperature = 0.7
top_p = 0.9
