[dungeon]
grammar_file = "grammars/classic.toml"
iterations = 4

[dungeon.symbols]
F = { label = "Mineshaft corridor",  tags = ["cobblestone", "oak-supports", "torchlit"] }
K = { label = "Enchantment shrine",  tags = ["arcane", "books", "glyphs"] }
M = { label = "Spider lair",         tags = ["webs", "chitin", "danger"] }
V = { label = "Villager trader post", tags = ["market", "lanterns", "barter"] }

[ollama]
endpoint = "https://341f48ced197.ngrok-free.app"
completion_path = "/v1/completions"
model = "deepseek-r1:1.5b"
timeout = 120
prompt_file = "prompts/default_prompts.toml"

[ollama.options]
temperature = 0.7
top_p = 0.9

[content.items.symbols]
T = { label = "Torch",               tags = ["light", "oak", "flicker"] }
P = { label = "Potion of Healing",   tags = ["potion", "red", "splash"] }
L = { label = "Empty Map",           tags = ["paper", "cartography", "blank"] }
G = { label = "Emerald",             tags = ["currency", "green", "shiny"] }
O = { label = "Ender Pearl",         tags = ["teleport", "void", "fragile"] }
R = { label = "Redstone Dust",       tags = ["circuit", "powder", "glowing"] }
B = { label = "Bone",                tags = ["mob-drop", "white", "stack"] }
C = { label = "Coal",                tags = ["fuel", "black", "lump"] }

[content.items.grammars]
# F/K/M — как раньше; для V используем «богатый» лут святилища.
F = "grammars/items/corridor.toml"
K = "grammars/items/shrine.toml"
M = "grammars/items/lair.toml"
V = "grammars/items/shrine.toml"

[content.monsters.symbols]
# Символы монстров остаются прежними (S,W,H,V,F,N), но лейблы под Minecraft:
S = { label = "Skeleton",   tags = ["ranged", "bones", "ambush"] }
W = { label = "Witch",      tags = ["potion", "cackle", "hex"] }
H = { label = "Husk",       tags = ["desert", "zombie", "dry"] }
V = { label = "Vindicator", tags = ["illager", "axe", "hostile"] }
F = { label = "Cave Spider",tags = ["poison", "webs", "swift"] }
N = { label = "Zombie",     tags = ["undead", "groan", "melee"] }

[content.monsters.grammars]
# F/K/M — как раньше; для V берём «сдержанную» частоту встреч как у святилища.
F = "grammars/monsters/corridor.toml"
K = "grammars/monsters/shrine.toml"
M = "grammars/monsters/lair.toml"
V = "grammars/monsters/shrine.toml"

[evaluation]
candidate_count = 10
target_room_count = 30

[evaluation.weights]
# Рекомендация под Майнкрафт-шахту: поощряем разнообразие комнат и разветвления,
# умеренно ценим присутствие лута и монстров, штрафуем тупики.
room_diversity   = 1.2
branching_factor = 1.0
loot_presence    = 0.6
monster_presence = 0.35
dead_end_penalty = -0.7
room_count       = 0.3